name: Compile parsers

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        target:
          - x86_64-linux
          - aarch64-linux
          - x86_64-windows
    env:
      ZIG_TARGET: ${{ matrix.target }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: mlugg/setup-zig@v2.0.5
        with:
          version: 0.15.1
      - name: Install tree-sitter-cli
        run: npm install tree-sitter-cli
      - name: Compile parsers
        run: |
          zig build \
          --prefix out \
          --summary=all \
          "-Dtarget=$ZIG_TARGET" \
          -Drelease=true
      - name: compress parsers
        run: |
          OUTPUT_FILE="parsers-${ZIG_TARGET}.tar.zst"
          tar -I zstd -cf "$OUTPUT_FILE" -C out .
          echo "OUTPUT_FILE=${OUTPUT_FILE}" >> "$GITHUB_ENV"
      - name: upload parsers
        run: |
          TAG=$(gh release list --json 'tagName,isLatest' -q 'map(select(.isLatest))[0].tagName')
          gh release upload "$TAG" "$OUTPUT_FILE" --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

